require("bigcreto.plugins.lsp")
require("bigcreto.plugins.treesitter")
require("bigcreto.plugins.lualine")
require("bigcreto.plugins.nvimtree")
require("bigcreto.plugins.telescope")
require("bigcreto.plugins.nvim-cmp")
